Nested proofs cause proof to fail in Coq 8.8.0
The following error occurs:

  Error: Anomaly "Uncaught exception Not_found."

Pulling the auxiliary results out of the concerned lemma solves the
problem.